[workspace]
members = [
	"node",
	"pallets/*",
	"pallets/urauth/runtime-api",
	"runtime",
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
